- name: CIS Hardening
  hosts: app
  become: true
  gather_facts: true


  vars:
    amzn2023cis_rule_4_6_6: false # dissable password expiration for root
    amzn2023cis_rule_1_3_1: false # disable AIDE
    amzn2023cis_rule_1_3_3: false




  roles:
    - AMAZON2023-CIS